FROM tiangolo/uvicorn-gunicorn:python3.11-slim

RUN apt-get update && apt-get install -y netcat-traditional

COPY requirements.txt .
RUN pip install -r requirements.txt

# just in case, install curl
RUN apt-get update && apt-get install -y curl

COPY . .
